# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/adam/COMSE6424/ZedBoard/K9F1G08U0E_controller/K9F1G08U0E_controller.srcs/sources_1/bd/bd/ip/bd_xbar_0/bd_xbar_0.xci
# IP: The module: 'bd_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/adam/COMSE6424/ZedBoard/K9F1G08U0E_controller/K9F1G08U0E_controller.srcs/sources_1/bd/bd/ip/bd_xbar_0/bd_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/adam/COMSE6424/ZedBoard/K9F1G08U0E_controller/K9F1G08U0E_controller.srcs/sources_1/bd/bd/ip/bd_xbar_0/bd_xbar_0.xci
# IP: The module: 'bd_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/adam/COMSE6424/ZedBoard/K9F1G08U0E_controller/K9F1G08U0E_controller.srcs/sources_1/bd/bd/ip/bd_xbar_0/bd_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
