# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constrs_2/zedboard_master_XDC_RevC_D_v3.xdc

# Block Designs: bd/bd/bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd || ORIG_REF_NAME==bd} -quiet] -quiet

# IP: bd/bd/ip/bd_processing_system7_0_3/bd_processing_system7_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_processing_system7_0_3 || ORIG_REF_NAME==bd_processing_system7_0_3} -quiet] -quiet

# IP: bd/bd/ip/bd_NAND_Flash_Controller_0_0/bd_NAND_Flash_Controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_NAND_Flash_Controller_0_0 || ORIG_REF_NAME==bd_NAND_Flash_Controller_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_ps7_0_axi_periph_0/bd_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/bd/ip/bd_rst_ps7_0_100M_0/bd_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_rst_ps7_0_100M_0 || ORIG_REF_NAME==bd_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/bd/ip/bd_auto_pc_0/bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_auto_pc_0 || ORIG_REF_NAME==bd_auto_pc_0} -quiet] -quiet

# XDC: bd/bd/bd_ooc.xdc
